cmake_minimum_required(VERSION 3.21)
file(REMOVE_RECURSE "${DIRECTORY}")
execute_process(COMMAND "${LAUNCHER}" --prepare-only --credentials "${DIRECTORY}" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Credential generation failed")
endif()
foreach(name cert.pem key.pem token)
    file(SHA256 "${DIRECTORY}/${name}" "before_${name}")
endforeach()
file(READ "${DIRECTORY}/token" token)
string(STRIP "${token}" token)
string(LENGTH "${token}" length)
if(NOT length EQUAL 64 OR NOT token MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid development token")
endif()
execute_process(COMMAND "${LAUNCHER}" --prepare-only --credentials "${DIRECTORY}" --page-url http://127.0.0.1:8899/ui/ --quic-port 4444 RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Credential reuse failed")
endif()
foreach(name cert.pem key.pem token)
    file(SHA256 "${DIRECTORY}/${name}" after)
    if(NOT after STREQUAL "${before_${name}}")
        message(FATAL_ERROR "Existing credentials changed: ${name}")
    endif()
endforeach()
file(READ "${DIRECTORY}/url.txt" url)
if(NOT url MATCHES "^http://127.0.0.1:8899/ui/#wt-url=https%3A%2F%2F127.0.0.1%3A4444%2Fwt&wt-token=${token}&wt-cert=[0-9a-f]+")
    message(FATAL_ERROR "Invalid connection URL")
endif()
file(RENAME "${DIRECTORY}/token" "${DIRECTORY}/saved-token")
execute_process(COMMAND "${LAUNCHER}" --prepare-only --credentials "${DIRECTORY}" RESULT_VARIABLE status)
if(status EQUAL 0 OR EXISTS "${DIRECTORY}/token")
    message(FATAL_ERROR "Partial credentials must fail without replacing files")
endif()
