cmake_minimum_required(VERSION 3.21)

# Offline contract test: package dependencies must be ready before the two
# vcpkg configure processes start. The manifest-consumer CI job tests the real
# downloads, compilation, installation and exported package separately.
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED WORK)
    message(FATAL_ERROR "Pass -DWORK=<temporary test directory>")
endif()
if(NOT DEFINED PORTFILE)
    set(PORTFILE "${ROOT}/ports/imgui-quic/portfile.cmake")
endif()
set(ENV{IMGUI_QUIC_LOCAL_SOURCE_DIR} "${ROOT}")
set(CURRENT_BUILDTREES_DIR "${WORK}/buildtrees")
set(CURRENT_PACKAGES_DIR "${WORK}/packages")
set(VCPKG_LIBRARY_LINKAGE static)

function(vcpkg_from_git)
    cmake_parse_arguments(arg "" "OUT_SOURCE_PATH;URL;REF" "" ${ARGN})
    if(arg_URL STREQUAL "https://github.com/ocornut/imgui.git")
        set(source "${WORK}/imgui")
        file(MAKE_DIRECTORY "${source}")
        file(WRITE "${source}/imgui.h" "// fixture\n")
        file(WRITE "${source}/LICENSE.txt" "ImGui license fixture\n")
    elseif(arg_URL STREQUAL "https://github.com/lz4/lz4.git")
        file(READ "${ROOT}/cmake/Lz4.cmake" lz4_cmake)
        string(REGEX MATCH "set\\(IMGUI_QUIC_LZ4_REVISION \"([0-9a-f]+)\"\\)" pin "${lz4_cmake}")
        if(NOT pin OR NOT arg_REF STREQUAL CMAKE_MATCH_1)
            message(FATAL_ERROR "The port must use the Lz4.cmake revision")
        endif()
        set(source "${WORK}/lz4")
        file(MAKE_DIRECTORY "${source}/lib")
        foreach(name lz4.c lz4.h LICENSE)
            file(WRITE "${source}/lib/${name}" "LZ4 fixture: ${name}\n")
        endforeach()
    else()
        message(FATAL_ERROR "Unexpected dependency URL: ${arg_URL}")
    endif()
    set(${arg_OUT_SOURCE_PATH} "${source}" PARENT_SCOPE)
endfunction()

function(vcpkg_cmake_configure)
    cmake_parse_arguments(arg "" "SOURCE_PATH" "OPTIONS" ${ARGN})
    foreach(name lz4.c lz4.h LICENSE)
        set(path "${arg_SOURCE_PATH}/third_party/lz4/lib/${name}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "LZ4 must be pre-seeded before configure: ${name}")
        endif()
        file(READ "${path}" contents)
        if(NOT contents STREQUAL "LZ4 fixture: ${name}\n")
            message(FATAL_ERROR "The port did not copy the fetched LZ4 source: ${name}")
        endif()
    endforeach()
    set(configure_checked TRUE PARENT_SCOPE)
endfunction()

function(vcpkg_cmake_install)
endfunction()
function(vcpkg_cmake_config_fixup)
endfunction()
function(vcpkg_install_copyright)
    cmake_parse_arguments(arg "" "COMMENT" "FILE_LIST" ${ARGN})
    if(NOT "${LZ4_SOURCE_PATH}/lib/LICENSE" IN_LIST arg_FILE_LIST)
        message(FATAL_ERROR "The port must install the LZ4 library license")
    endif()
    set(copyright_checked TRUE PARENT_SCOPE)
endfunction()

include("${PORTFILE}")
if(NOT configure_checked OR NOT copyright_checked)
    message(FATAL_ERROR "The port did not run all expected packaging steps")
endif()
message(STATUS "vcpkg port: pinned LZ4 pre-seeding and license checks passed")
