cmake_minimum_required(VERSION 3.21)
foreach(required ROOT BUILD SOURCE JOBS ARCH)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
find_package(Git REQUIRED)
find_program(CLANG clang REQUIRED)
find_program(CLANGXX clang++ REQUIRED)
file(READ "${ROOT}/transport/quiche/dependencies.json" pins)
string(JSON revision GET "${pins}" quiche_commit)
string(JSON version GET "${pins}" bazel_version)
string(JSON expected GET "${pins}" bazel_sha256 "${ARCH}")
file(MAKE_DIRECTORY "${BUILD}/tools")
function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGV}")
    endif()
endfunction()
if(NOT EXISTS "${SOURCE}")
    run("${GIT_EXECUTABLE}" init "${SOURCE}")
    run("${GIT_EXECUTABLE}" -C "${SOURCE}" fetch --depth=1 https://github.com/google/quiche.git "${revision}")
    run("${GIT_EXECUTABLE}" -C "${SOURCE}" checkout --detach FETCH_HEAD)
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE}" rev-parse HEAD OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT actual STREQUAL revision)
    message(FATAL_ERROR "QUICHE source must be pinned to ${revision}: ${SOURCE}")
endif()
file(MAKE_DIRECTORY "${SOURCE}/quiche/imgw")
foreach(name server.cc bridge.h protocol.h exports.map)
    configure_file("${ROOT}/transport/quiche/${name}" "${SOURCE}/quiche/imgw/${name}" COPYONLY)
endforeach()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE}" show HEAD:quiche/BUILD.bazel OUTPUT_VARIABLE original RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot read pinned QUICHE build manifest")
endif()
file(READ "${ROOT}/transport/quiche/BUILD.fragment" overlay)
file(WRITE "${SOURCE}/quiche/BUILD.bazel" "${original}\n${overlay}")
set(bazel "${BUILD}/tools/bazel-${version}-${ARCH}")
set(actual "")
if(EXISTS "${bazel}")
    file(SHA256 "${bazel}" actual)
endif()
if(NOT actual STREQUAL expected)
    file(DOWNLOAD "https://releases.bazel.build/${version}/release/bazel-${version}-linux-${ARCH}" "${bazel}.download" EXPECTED_HASH "SHA256=${expected}" TLS_VERIFY ON)
    file(CHMOD "${bazel}.download" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    file(RENAME "${bazel}.download" "${bazel}")
endif()
set(ENV{CC} "${CLANG}")
set(ENV{CXX} "${CLANGXX}")
execute_process(COMMAND "${bazel}" "--output_user_root=${BUILD}/bazel" build -c opt "--jobs=${JOBS}" --lockfile_mode=error //quiche:libimgui_quic_quiche.so WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "QUICHE build failed")
endif()
foreach(key bazel-bin output_base)
    execute_process(COMMAND "${bazel}" "--output_user_root=${BUILD}/bazel" info -c opt "${key}" WORKING_DIRECTORY "${SOURCE}" OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot resolve Bazel ${key}")
    endif()
    set("${key}" "${value}")
endforeach()
configure_file("${bazel-bin}/quiche/libimgui_quic_quiche.so" "${BUILD}/libimgui_quic_quiche.so.tmp" COPYONLY)
file(RENAME "${BUILD}/libimgui_quic_quiche.so.tmp" "${BUILD}/libimgui_quic_quiche.so")
set(EXTERNAL "${output_base}/external")
include("${ROOT}/cmake/QuicNotices.cmake")
