# Preserve upstream licenses, including nested BoringSSL notices.
file(GLOB dependencies LIST_DIRECTORIES true "${EXTERNAL}/*")
set(roots "${SOURCE}")
set(found_boringssl FALSE)
foreach(path IN LISTS dependencies)
    get_filename_component(name "${path}" NAME)
    if(IS_DIRECTORY "${path}" AND NOT name MATCHES "^@")
        list(APPEND roots "${path}")
        if(name MATCHES "boringssl")
            set(found_boringssl TRUE)
        endif()
    endif()
endforeach()
if(NOT EXISTS "${SOURCE}/LICENSE" OR NOT found_boringssl)
    message(FATAL_ERROR "Missing QUICHE/BoringSSL source notices")
endif()
set(output "${BUILD}/QUIC_THIRD_PARTY_NOTICES.txt.tmp")
file(WRITE "${output}" "Google QUICHE and dependencies. Pins: transport/quiche/dependencies.json and upstream MODULE.bazel.lock.\n")
foreach(root IN LISTS roots)
    get_filename_component(name "${root}" NAME)
    set(files "")
    foreach(pattern LICENSE* LICENCE* COPYING* NOTICE*)
        file(GLOB matches LIST_DIRECTORIES false "${root}/${pattern}")
        list(APPEND files ${matches})
        if(root STREQUAL SOURCE OR name MATCHES "boringssl")
            file(GLOB_RECURSE matches LIST_DIRECTORIES false "${root}/${pattern}")
            list(APPEND files ${matches})
        endif()
    endforeach()
    list(REMOVE_DUPLICATES files)
    list(SORT files)
    foreach(path IN LISTS files)
        file(RELATIVE_PATH relative "${root}" "${path}")
        if(NOT relative MATCHES "bazel-")
            file(READ "${path}" content)
            file(APPEND "${output}" "\n=== ${name}/${relative} ===\n${content}\n")
        endif()
    endforeach()
endforeach()
file(RENAME "${output}" "${BUILD}/QUIC_THIRD_PARTY_NOTICES.txt")
